[2023-09-29T22:01:56.136+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_jugantor manual__2023-09-29T22:01:54.300799+00:00 [queued]>
[2023-09-29T22:01:56.153+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_jugantor manual__2023-09-29T22:01:54.300799+00:00 [queued]>
[2023-09-29T22:01:56.153+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:01:56.177+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_jugantor> on 2023-09-29 22:01:54.300799+00:00
[2023-09-29T22:01:56.184+0000] {standard_task_runner.py:57} INFO - Started process 1010 to run task
[2023-09-29T22:01:56.188+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_jugantor', 'manual__2023-09-29T22:01:54.300799+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmp2swhyvl6']
[2023-09-29T22:01:56.194+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask extract_jugantor
[2023-09-29T22:01:56.247+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_jugantor manual__2023-09-29T22:01:54.300799+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:01:56.336+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_jugantor' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T22:01:54.300799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-29T22:01:54.300799+00:00'
[2023-09-29T22:01:56.345+0000] {extract.py:22} ERROR - Could not fetch content due to error: HTTPSConnectionPool(host='www.jugantor.com', port=443): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9112b26520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-09-29T22:01:56.346+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/extract.py", line 43, in parse_from_jugantor
    all_links = sitemap_soup.find_all('loc')
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-09-29T22:01:56.354+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Pipeline, task_id=extract_jugantor, execution_date=20230929T220154, start_date=20230929T220156, end_date=20230929T220156
[2023-09-29T22:01:56.371+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task extract_jugantor ('NoneType' object has no attribute 'find_all'; 1010)
[2023-09-29T22:01:56.405+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T22:01:56.441+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
